language: rust
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

matrix:
  include:
    - rust: 1.18.0
    - rust: stable
    - rust: stable
      os: osx
    - rust: beta
    - rust: nightly
      script:
        - cargo test --all
        - cargo test --all --features nightly
        - cargo test --all --benches
        - cargo build --all --no-default-features
        - cargo doc --no-deps --features nightly
script:
  - cargo test --all
  - cargo build --all --no-default-features
after_success:
  - travis-cargo --only nightly doc-upload
env:
  global:
    secure: "BdDntVHSompN+Qxz5Rz45VI4ZqhD72r6aPl166FADlnkIwS6N6FLWdqs51O7G5CpoMXEDvyYrjmRMZe/GYLIG9cmqmn/wUrWPO+PauGiIuG/D2dmfuUNvSTRcIe7UQLXrfP3yyfZPgqsH6pSnNEVopquQKy3KjzqepgriOJtbyY="

notifications:
  email:
    on_success: never
