[package]
name = "rand"
version = "0.3.17"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang-nursery/rand"
documentation = "https://docs.rs/rand"
homepage = "https://github.com/rust-lang-nursery/rand"
description = """
Random number generators and other randomness functionality.
"""
keywords = ["random", "rng"]
categories = ["algorithms"]

[features]
default = ["std"]
nightly = ["i128_support"]

i128_support = ["rand_core/i128_support"]

# Deps should use 'std' if we do:
std = ["rand_core/std", "libc"]

[dependencies]
# All deps must not use 'std' by default
libc = { version = "0.2", optional = true }
rand_core = { path = 'rand_core', default-features = false }

[target.'cfg(target_os = "fuchsia")'.dependencies]
fuchsia-zircon = "^0.2.1"

[workspace]
members = ["rand_core"]
