[package]
name = "rand"
version = "0.3.16"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang-nursery/rand"
documentation = "https://docs.rs/rand"
homepage = "https://github.com/rust-lang-nursery/rand"
description = """
Random number generators and other randomness functionality.
"""
keywords = ["random", "rng"]
categories = ["algorithms"]

[features]
default = ["std"]
nightly = ["i128_support"]
std = []
i128_support = ["rand_core/i128_support"]

[dependencies]
libc = "0.2"
rand_core = { path = 'rand_core' }

[target.'cfg(target_os = "fuchsia")'.dependencies]
magenta = "^0.1.1"

[workspace]
members = ["rand_core"]
