[package]
name = "rand_core"
version = "0.0.1"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang-nursery/rand"
documentation = "https://docs.rs/rand_core"
homepage = "https://github.com/rust-lang-nursery/rand"
description = """
Random number generator traits
"""
keywords = ["random", "rng"]
categories = ["algorithms"]

[features]
default = ["std"]
nightly = ["i128_support"]
std = []
i128_support = []
